basic.forever(function () {
	
})
basic.forever(function () {
    basic.showLeds(`
        # # # # #
        # # # # #
        # # # # #
        # # # # #
        # # # # #
        `)
    led.unplot(0, 0)
    basic.pause(100)
    led.unplot(4, 0)
    basic.pause(100)
    led.unplot(4, 4)
    basic.pause(100)
    led.unplot(3, 4)
    basic.pause(100)
    led.unplot(2, 4)
    basic.pause(100)
    led.unplot(1, 4)
    basic.pause(100)
    led.unplot(0, 4)
    basic.pause(100)
    led.unplot(0, 2)
    basic.pause(100)
    led.unplot(0, 1)
    basic.pause(100)
    led.unplot(1, 1)
    basic.pause(100)
    led.unplot(1, 0)
    basic.pause(100)
    led.unplot(2, 0)
    basic.pause(100)
    led.unplot(3, 0)
    basic.pause(100)
    led.unplot(3, 1)
    basic.pause(100)
    led.unplot(4, 1)
    basic.pause(100)
    led.unplot(4, 2)
    basic.pause(100)
    led.unplot(1, 2)
    basic.pause(100)
    led.unplot(2, 1)
    basic.pause(100)
    led.unplot(0, 3)
    basic.pause(100)
    led.unplot(3, 2)
    basic.pause(100)
    led.unplot(4, 3)
    basic.pause(100)
    led.unplot(2, 3)
    basic.pause(100)
})
